Pass test for providers/database
Signed-off-by: Shunsuke Tamiya <shunsuketamiya@posteo.net>

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,11 +1,27 @@
 #! /bin/sh
 
-# To enable this hook, rename this file to "pre-commit" and move it .git/hooks/.
+# Copyright 2012 The Go Authors. All rights reserved.
+# Use of this source code is governed by a BSD-style
+# license that can be found in the LICENSE file.
 
-docker-compose down && \
-    sudo chown -R $USER:$USER . && \
-    docker-compose build && \
-    docker-compose run web /usr/local/go/bin/go test -v \
-		   /go/src/github.com/ablce9/go-assignment/adapters/http \
-		   /go/src/github.com/ablce9/go-assignment/domain \
-		   /go/src/github.com/ablce9/go-assignment/providers/database
+# git gofmt pre-commit hook
+#
+# To use, store as .git/hooks/pre-commit inside your repository and make sure
+# it has execute permissions.
+#
+# This script does not handle file names that contain spaces.
+
+gofiles=$(git diff --name-only --diff-filter=ACM | grep '\.go$')
+[ -z "$gofiles" ] && exit 0
+
+unformatted=$(gofmt -l $gofiles)
+[ -z "$unformatted" ] && exit 0
+
+# Some files are not gofmt'd. Print message and fail.
+
+echo >&2 "Go files must be formatted with gofmt. Please run:"
+for fn in $unformatted; do
+    echo >&2 "  gofmt -w $PWD/$fn"
+done
+
+exit 1
